apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mlops-platform-operators
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - strimzi-operator.yaml
  - minio-operator.yaml
  - spark-operator.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: mlops-platform
      app.kubernetes.io/component: operators
      app.kubernetes.io/version: v1.0.0
      app.kubernetes.io/managed-by: flux

commonAnnotations:
  flux.weave.works/automated: "true"
  flux.weave.works/tag.chart: semver:~1.0
