apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 10m
  url: https://operator.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: operator
      version: "6.0.4"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
  targetNamespace: platform-operators
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    console:
      enabled: true
      ingress:
        enabled: false
