apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: strimzi
  namespace: flux-system
spec:
  interval: 10m
  url: https://strimzi.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.43.0"
      sourceRef:
        kind: HelmRepository
        name: strimzi
  targetNamespace: platform-operators
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    watchNamespaces:
      - data-plane
    defaultImageRegistry: quay.io
    defaultImageRepository: strimzi
    defaultImageTag: 0.43.0
