apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mlops-infrastructure
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/JeanFraga/MLOpsInfrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mlops-platform-base
  namespace: flux-system
spec:
  interval: 1m
  path: "./gitops/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: mlops-infrastructure
  timeout: 5m
  wait: true
  healthChecks:
    - apiVersion: v1
      kind: Namespace
      name: platform-operators
    - apiVersion: v1
      kind: Namespace
      name: data-plane
    - apiVersion: v1
      kind: Namespace
      name: orchestration
    - apiVersion: v1
      kind: Namespace
      name: ml-lifecycle
    - apiVersion: v1
      kind: Namespace
      name: processing-jobs
    - apiVersion: v1
      kind: Namespace
      name: observability
